apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
  name: keycloak-service-internal
  namespace: dev-support
  annotations:
    external-dns.alpha.kubernetes.io/hostname: os-dev-keycloak.dev-support.oruserv.com.br.
spec:
  type: "NodePort"
  externalTrafficPolicy: Local
  selector:
    app: keycloak
  ports:
    - port: 31389
      targetPort: 389
      protocol: TCP
      nodePort: 31389